# See https://github.com/hvr/multi-ghc-travis for more information

language: c

sudo: false

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.6.3
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.6.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - travis_retry cabal update
# workaround for https://ghc.haskell.org/trac/ghc/ticket/9221
 - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
 - cabal sandbox init
# can't use "cabal install --only-dependencies --enable-tests --enable-benchmarks" due to dep-cycle

script:
 - cabal configure 
 - cabal build
# "cabal check" disabled due to -O2 warning
# - cabal check
# check that the generated source-distribution can be built & installed

