# See https://github.com/hvr/multi-ghc-travis for more information

language: c

sudo: false

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.6.3
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.6.3], sources: [hvr-ghc]}}

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - travis_retry cabal update

script:
 - cabal configure 
 - cabal build